### ISSUE TITLE
coi_blast_db error

### ISSUE THREAD

**Issue by meglecz** [aitgon/vtam#30]
There is a problem of downloading the blast database with the command coi_blast_db. 
Curiously, the database is correctly downloaded from the example command.

```
mkdir ~/vtam_benchmark/vtam_db
cd  ~/vtam_benchmark/vtam_db
conda activate vtam

vtam coi_blast_db --blastdbdir coi_db

(vtam) 11:32 meglecz@bombyx ~/vtam_benchmark/vtam_db % vtam coi_blast_db --blastdbdir coi_db
Traceback (most recent call last):
  File "/home/meglecz/miniconda3/envs/vtam_2/bin/vtam", line 8, in <module>
    sys.exit(main())
  File "/home/meglecz/miniconda3/envs/vtam_2/lib/python3.7/site-packages/vtam/__init__.py", line 308, in main
    VTAM(sys.argv[1:])
  File "/home/meglecz/miniconda3/envs/vtam_2/lib/python3.7/site-packages/vtam/__init__.py", line 276, in __init__
    coi_blast_db.download(blastdbdir=blastdbdir)
  File "/home/meglecz/miniconda3/envs/vtam_2/lib/python3.7/site-packages/vtam/CommandBlastCOI.py", line 82, in download
    if not [*os.walk(blastdbdir)][0][2] >= blast_files or pathlib.Path(os.path.join(blastdbdir, "%s.nsq"%self.blastdbname)).stat().st_size < 4000000:
IndexError: list index out of range
zsh: exit 1     vtam coi_blast_db --blastdbdir coi_db
```

**Comment by aitgon** [comment]
Looks like a bug in  "CommandBlastCOI.py", line 82.
