### ISSUE TITLE
Getting ValueError when running taxassign with NCBI db

### ISSUE THREAD

**Issue by MarionDFO** [aitgon/vtam#32]
Hi, 

I got an error message when running the vtam taxassign command with a freshly downloaded NCBI db, I am working with Blast v2.13.0. Do you know what is the issue here? Thank you!

`(vtam3) genpop@Genpop:~/anaconda3/envs/vtam3/12S_SG_2021$ vtam taxassign --db run1/db.sqlite --asvtable run1/asvtable_default.tsv --output run1/asvtable_default_taxa.tsv --taxonomy taxonomy.tsv --blastdbdir /media/genpop/My_Book/Marion/NCBI_db2 --blastdbname nt -v --log run1/vtam.log`

Traceback (most recent call last):
  File "/home/genpop/anaconda3/envs/vtam3/bin/vtam", line 8, in <module>
    sys.exit(main())
  File "/home/genpop/anaconda3/envs/vtam3/lib/python3.7/site-packages/vtam/__init__.py", line 308, in main
    VTAM(sys.argv[1:])
  File "/home/genpop/anaconda3/envs/vtam3/lib/python3.7/site-packages/vtam/__init__.py", line 237, in __init__
    blastdbname_str=blastdbname_str, params=params, num_threads=num_threads)
  File "/home/genpop/anaconda3/envs/vtam3/lib/python3.7/site-packages/vtam/CommandTaxAssign.py", line 180, in main
    params = None)
  File "/home/genpop/anaconda3/envs/vtam3/lib/python3.7/site-packages/vtam/utils/RunnerTaxAssign.py", line 73, in __init__
    blast_output_df = RunnerBlast.process_blast_result(blast_output_tsv)
  File "/home/genpop/anaconda3/envs/vtam3/lib/python3.7/site-packages/vtam/utils/RunnerBlast.py", line 96, in process_blast_result
    expand=True)
  File "/home/genpop/anaconda3/envs/vtam3/lib/python3.7/site-packages/pandas/core/generic.py", line 5516, in __setattr__
    self[name] = value
  File "/home/genpop/anaconda3/envs/vtam3/lib/python3.7/site-packages/pandas/core/frame.py", line 3602, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/genpop/anaconda3/envs/vtam3/lib/python3.7/site-packages/pandas/core/frame.py", line 3729, in _set_item_frame_value
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key

**Comment by meglecz** [comment]
Hi Marion,

Have you created the taxonomy file from new ?

`vtam taxonomy --output taxonomy.tsv`

There are probably new taxids in the newly dowloaded ncbi database that are not in the precomputed taxonomy.tsv file.

Which marker are you using ?

Emese

**Comment by MarionDFO** [comment]
Hi Emese, 

Yes I've created the taxonomy file from new with your taxonomy function from VTAM after downloading NCBI nt db (not a specific marker, all the db).
Thanks, 
Marion
