### ISSUE TITLE
Pb of taxassign with ncbi nt database

### ISSUE THREAD

**Issue by meglecz** [aitgon/vtam#9]
vtam taxassign is running OK with custom database, but when using a freshly downloaded  ncbi-nt (2021-04-26), I have an error message. (see bellow)

This is true when running vtam in an updated conda environment and also from singularity.

blast versions are the following:
Singularity> blastn -version
blastn: 2.5.0+
 Package: blast 2.5.0, build Sep 20 2018 01:34:18
 
 (vtam) emese@pcf-meglecz:~/singularity$ blastn -version
blastn: 2.2.31+
Package: blast 2.2.31, build Jan  7 2016 23:17:17

Error msg:

Traceback (most recent call last):
  File "/opt/conda/envs/vtam/bin/vtam", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/vtam/lib/python3.9/site-packages/vtam/__init__.py", line 273, in main
    VTAM(sys.argv[1:])
  File "/opt/conda/envs/vtam/lib/python3.9/site-packages/vtam/__init__.py", line 215, in __init__
    CommandTaxAssign.main(db=db, mode=mode, asvtable_tsv=asvtable_tsv, output=output,
  File "/opt/conda/envs/vtam/lib/python3.9/site-packages/vtam/CommandTaxAssign.py", line 174, in main
    tax_assign_runner = RunnerTaxAssign(
  File "/opt/conda/envs/vtam/lib/python3.9/site-packages/vtam/utils/RunnerTaxAssign.py", line 71, in __init__
    blast_output_tsv = runner_blast.run_local_blast()
  File "/opt/conda/envs/vtam/lib/python3.9/site-packages/vtam/utils/RunnerBlast.py", line 68, in run_local_blast
    stdout, stderr = blastn_cline()
  File "/opt/conda/envs/vtam/lib/python3.9/site-packages/Bio/Application/__init__.py", line 569, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 2 from 'blastn -out /tmp/tmps_xrub66/RunnerBlast.py/blast_output.tsv -outfmt "6 qseqid sacc pident evalue qcovhsp staxids" -query /tmp/tmps_xrub66/RunnerTaxAssign.py/variant.fasta -db nt -evalue 1e-05 -qcov_hsp_perc 80 -num_threads 8 -dust yes', message 'BLAST Database error: Error: Not a valid version 4 database.'

**Comment by aitgon** [comment]
This looks related to this issue bxlab/metaWRAP#266

It says that you must upgrade to blast+ 2.8.1 with the latest database

**Comment by meglecz** [comment]
Thanks! It works with blastn: 2.9.0+ in the conda enviroment both with ncbi-nt and the custom database (coi_blast_db_20200420)

Could you change the singularity recepie file to get the latest BLAST version, please?

**Comment by aitgon** [comment]
I have updated the singularity definition file with the more recent blastn 2.10.1 here: b1acfa91843291bab2ba943cd9a80588d13a3bb4

Can you check it?

**Comment by meglecz** [comment]
It is working. Thanks!
